<?php

/**
 * Mavgento
 *
 *
 *
 * @category    Mavgento
 * @package     Mavgento_Custombanner
 * @copyright   
 * @license     
 */

?>
<?php
/** @var \Mavgento\Custombanner\Block\SliderItem $block */
$styleSlide = $block->getSlider()->getStyleSlide();
$slider = $block->getSlider();
$htmlId   = $block->getFlexsliderHtmlId();
$bannerCollection = $block->getBannerCollection();
?>
<link rel="stylesheet" type="text/css" href="<?php echo $block->getViewFileUrl('Mavgento_Custombanner::css/flexslider.css')?>">
<link rel="stylesheet" type="text/css" href="<?php echo $block->getViewFileUrl('Mavgento_Custombanner::css/custom.css')?>">
<script type="text/javascript">
(function  () {
    var flexSliderSelector = '<?php echo $htmlId; ?>';
    require(['jquery', 'mavgento/flexslider'], function($) {
        var fitImageSlider = function (slider) {
            if(slider && slider[0]) {
                var height = $(slider[0]).find('.slides li img').height();
                $(slider[0]).find('.slides li img').each(function(index, element){
                    if($(element).height() > height) {
                        height = $(element).height();
                    }
                });
                $(slider[0]).find('.slides li,.slides  li a,.slides li img').css('height', height + 'px');
            }
        }
        $(document).ready(function($) {
            var STYLESLIDE_FLEXSLIDER_ONE = <?php echo \Mavgento\Custombanner\Model\Slider::STYLESLIDE_FLEXSLIDER_ONE ?>;
            var STYLESLIDE_FLEXSLIDER_TWO = <?php echo \Mavgento\Custombanner\Model\Slider::STYLESLIDE_FLEXSLIDER_TWO ?>;
            var STYLESLIDE_FLEXSLIDER_THREE = <?php echo \Mavgento\Custombanner\Model\Slider::STYLESLIDE_FLEXSLIDER_THREE ?>;

            switch (<?php echo $styleSlide ?>) {
                case STYLESLIDE_FLEXSLIDER_ONE:
                    $('.' + flexSliderSelector).flexslider({
                        animation: '<?php echo $block->escapeHtml($slider->getData("animationB")); ?>',
                        slideshowSpeed: <?php echo $slider->getSliderSpeed() ?>,
                        start: function (slider) {
                            fitImageSlider(slider);
                        }
                    });
                    break;
                case STYLESLIDE_FLEXSLIDER_TWO:
                    $('.' + flexSliderSelector).flexslider({
                        animation: '<?php echo $block->escapeHtml($slider->getData("animationB")) ?>',
                        controlNav: 'thumbnails',
                        slideshowSpeed: <?php echo $slider->getSliderSpeed() ?>,
                        start: function (slider) {
                            fitImageSlider(slider);
                        }
                    });
                    break;
                case STYLESLIDE_FLEXSLIDER_THREE:
                    $('#'+flexSliderSelector + '-carousel').flexslider({
                        animation: 'slide',
                        controlNav: false,
                        animationLoop: true,
                        slideshow: true,
                        itemWidth: 210,
                        itemMargin: 5,
                        asNavFor: '#' + flexSliderSelector,
                        start: function (slider) {
                            fitImageSlider(slider);
                        }
                    });
                    $('#' + flexSliderSelector).flexslider({
                        animation: '<?php echo $block->escapeHtml($slider->getData("animationB")) ?>',
                        controlNav: false,
                        animationLoop: true,
                        slideshow: true,
                        sync: '#'+flexSliderSelector + '-carousel',
                        slideshowSpeed: <?php echo $slider->getSliderSpeed() ?>,
                        start: function (slider) {
                            fitImageSlider(slider);
                        }
                    });
                    break;
                default:
                    $('.' + flexSliderSelector).flexslider({
                        animation: 'slide',
                        animationLoop: true,
                        itemWidth: 400,
                        slideshow: true,
                        itemMargin: 5,
                        minItems: 2,
                        maxItems: 4,
                        start: function (slider) {
                            fitImageSlider(slider);
                        }
                    });
                    break;
            }

        });
    });
})();
</script>
<div class="mavgento-custombanner-standard" data-mage-init='{"mavgento/impress": {"url": "<?php echo $this->getUrl("custombanner/index/impress") ?>", "slider_id": "<?php echo $block->getSlider()->getId() ?>"}}'>
    <?php if ($block->isShowTitle() == \Mavgento\Custombanner\Model\Slider::SHOW_TITLE_YES) :
    ?>
        <div class="mavgento-custombanner-title" style="font: bold 12px/16px Arial, Helvetica, sans-serif;text-transform: uppercase;color: #e26703;">
        <strong><span><?php echo $block->escapeHtml($slider->getTitle()); ?></span></strong>
        </div>
    <?php endif; ?>
    <div class="mavgento-bannerslide-flex-slider" style="margin: auto; margin-bottom: 40px;">
        <div id="<?php echo $htmlId ?>" class="flexslider flexslider-content-image <?php echo $htmlId ?>" style="margin:auto">
            <ul class="slides">
                <?php foreach ($bannerCollection as $banner):
                ?>
                    <?php if ($styleSlide == \Mavgento\Custombanner\Model\Slider::STYLESLIDE_FLEXSLIDER_TWO) : ?>
                    <li data-thumb="<?php echo $block->getBannerImageUrl($banner) ?>">
                        <a href="<?php echo $banner->getClickUrl() ?>" target="<?php echo $banner->getTargetValue() ?>" style="display:block;" data-mage-init='{"mavgento/clickbanner": {"url": "<?php echo $this->getUrl("custombanner/index/click") ?>", "slider_id": "<?php echo $banner->getSliderId() ?>", "banner_id": "<?php echo $banner->getId() ?>" }}' >
                            <img alt="<?php echo $banner->getImageAlt() ?>" src="<?php echo $block->getBannerImageUrl($banner) ?>"/>
                        </a>
                        <?php if($banner->getCaption()): ?><div class="flex-caption"><?php echo $banner->getCaption(); ?></div><?php endif; ?>
                    </li>
                    <?php else :
                    ?>
                    <li>
                        <a href="<?php echo $banner->getClickUrl() ?>" target="<?php echo $banner->getTargetValue() ?>" style="display:block;" data-mage-init='{"mavgento/clickbanner": {"url": "<?php echo $this->getUrl("custombanner/index/click") ?>", "slider_id": "<?php echo $banner->getSliderId() ?>", "banner_id": "<?php echo $banner->getId() ?>" }}' >
                            <img alt="<?php echo $banner->getImageAlt() ?>"  src="<?php echo $block->getBannerImageUrl($banner) ?>"/>
                        </a>
                        <?php if($banner->getCaption()): ?><div class="flex-caption"><?php echo $banner->getCaption(); ?></div><?php endif; ?>
                    </li>
                    <?php endif; ?>
                <?php endforeach ?>
            </ul>
        </div>

        <?php if ($styleSlide ==  \Mavgento\Custombanner\Model\Slider::STYLESLIDE_FLEXSLIDER_THREE) :
        ?>
        <!-- for flex slide carousel-->
        <div id="<?php echo $htmlId ?>-carousel" class="flexslider flexslider-carousel" style="margin:auto">
            <ul class="slides">
                <?php foreach ($bannerCollection as $banner) :
                ?>
                    <li>
                        <img  alt="<?php echo $banner->getImageAlt() ?>" src="<?php echo $block->getBannerImageUrl($banner) ?>" />
                    </li>
                <?php endforeach ?>
            </ul>
        </div>
        <?php endif; ?>
    </div>
</div>
<style>
    .flex-viewport .slides li{
        margin-bottom: 0px !important;
    }
</style>